- examples/javascript/index.js
- examples/typescript/index.ts
- src/index.ts
The AuthCredentials classes were not being re-exported properly. Now they are.
Additionally, the examples have been updated to reflect this change, and demonstrate usage.
> Fix default exports

- src/backup/index.ts
- src/backup/journey.test.ts
- src/batch/index.ts
- src/batch/journey.test.ts
- src/c11y/index.ts
- src/classifications/index.ts
- src/classifications/knn.journey.test.ts
- src/cluster/index.ts
- src/connection/auth.ts
- src/connection/gqlClient.ts
- src/connection/httpClient.ts
- src/connection/index.ts
- src/data/index.ts
- src/data/journey.test.ts
- src/graphql/index.ts
- src/graphql/journey.test.ts
- src/index.ts
- src/misc/index.ts
- src/misc/openidConfigurationGetter.ts
- src/schema/index.ts
- src/schema/journey.test.ts
- src/utils/testData.ts
- remove the `I` prefix
- remove redundant `WeaviateClient` prefix
- rename oidc credentials inputs
> Rename interfaces to be more idiomatic

- src/connection/index.ts
- src/connection/journey.test.ts
> Sanitize connection parameters

- src/embedded/index.ts
- src/embedded/journey.test.ts
- Allow `'latest'` version to automatically download the latest Weaviate server version
- Support explicit URL to weaviate binary in the form of `binaryUrl` property of `EmbeddedOptions`
- Detect machine architecture to download correct binary
> Support 'latest' version, explicit binary URL for Embedded DB

- ci/compose.sh
- ci/docker-compose-cluster.yml
- src/graphql/getter.test.ts
- src/graphql/getter.ts
- src/graphql/journey.test.ts
Introduces `client.graphql.get().withConsistencyLevel()` to set desired consistency level per query.
Example:
```ts
import weaviate, { WeaviateClient } from 'weaviate-ts-client';
const client: WeaviateClient = weaviate.client({
scheme: 'http',
host: 'localhost:8080',
});
const resp = await client.graphql
.get()
.withClassName('Article')
.withFields('_additional { id isConsistent }')
.withConsistencyLevel('ONE')
.do();
console.log(`resp: ${JSON.stringify(resp)}`);
```
> Support GQL `Get{}` tunable consistency

- examples/typescript/index.ts
- package-lock.json
- package.json
- src/index.ts
- src/utils/uuid.ts
Introduces a `generateUuid5` function, which takes in any identifier and an optional namespace, to generate deterministic UUIDs.
Example: 
```ts
import { generateUuid5 } from 'weaviate-ts-client';
const withNamespace = generateUuid5('some-string-identifer', 'some-namespace');
console.log(withNamespace);
const withoutNamespace = generateUuid5('some-string-identifer');
console.log(withoutNamespace);
```
> UUIDv5 support

- src/connection/gqlClient.ts
Export fetch, in the case that cross-fetch (used by the gql client) is not supported in a given environment
Closes #54
> Support fetch in all environments

- src/schema/classExists.ts
- src/schema/index.ts
- src/schema/journey.test.ts
This PR introduces a method to the `schema` property of `client` that checks for the existence of a class within the database by its `className`.
In an effort to keep the implementation decoupled but logical, the `ClassExists` builder class is introduced that conforms to the logic of other builder classes within the `src/schema/` directory. The `do()` method of this class is, however, abstracted away from the end user such that they only access:
```typescript
const exists: boolean = await client
.schema
.exists('MyClass')
```
without the added overhead and complexity of making many builder calls to achieve the result. This was done to conform with the previously raised issue: https://github.com/weaviate/typescript-client/issues/16.
The implementation simply calls the `/schema` endpoint of …
> Add method to check if class exists

- src/data/checker.ts
- src/data/journey.test.ts
- src/data/path.ts
Resolves https://github.com/weaviate/typescript-client/issues/79
> Adds `.withConsistencyLevel` to `.checker` class

- src/connection/gqlClient.ts
- src/connection/httpClient.ts
- src/connection/index.ts
- src/connection/unit.test.ts
- src/index.ts
- test/server.ts
This `PR` aims to fix https://github.com/weaviate/typescript-client/issues/87 and adds a simple check before creating the `baseUrl`
```
const version = '/v1';
const baseUri = config.host.startsWith(`${config.scheme}://`)
? `${config.host}${version}`
: `${config.scheme}://${config.host}${version}`;
```
This allows users to use a host URL with a scheme if it matches the specified scheme.
The PR also adds two unit tests to verify that it constructs the correct URLs.
> Handle existing scheme in host

- .gitignore
- .prettierignore
- package-lock.json
- package.json
- src/proto/google/protobuf/struct.ts
- src/proto/v1/base.ts
- src/proto/v1/batch.ts
- src/proto/v1/search_get.ts
- src/proto/v1/weaviate.ts
- tools/refresh_protos.sh
This PR introduces the `ts-proto` development dependency in order to generate type-safe gRPC stubs for use when developing the new gRPC functionalities in the collections API
> Create gRPC stubs

- ci/docker-compose-azure-cc.yml
- ci/docker-compose-cluster.yml
- ci/docker-compose-okta-cc.yml
- ci/docker-compose-okta-users.yml
- ci/docker-compose-openai.yml
- ci/docker-compose-wcs.yml
- ci/docker-compose.yml
- package-lock.json
- package.json
- src/cluster/journey.test.ts
- src/connection/httpClient.ts
This PR replaces the `isomorphic-fetch` dependency with the now-fully-native `fetch` API. This means that the client is no longer compatible with any node versions less than 18. However, these versions are deprecated and have reached their complete EoL dates: https://endoflife.date/nodejs
This PR resolves issue number https://github.com/weaviate/typescript-client/issues/94
> bump CI image, replace isomorphic-fetch with fetch

- ci/docker-compose-azure-cc.yml
- ci/docker-compose-cluster.yml
- ci/docker-compose-okta-cc.yml
- ci/docker-compose-okta-users.yml
- ci/docker-compose-openai.yml
- ci/docker-compose-wcs.yml
- ci/docker-compose.yml
- src/cluster/journey.test.ts
- src/cluster/nodesStatusGetter.ts
Supports new `verbose` option in the Nodes API that has a server-side default of `minimal`. However, so as not to introduce a breaking client change, the client's default is `verbose`. This will default will be changed to `minimal` when Weaviate `1.24` releases to give a longer deprecation cycle
> make changes for 1.23 support

- .github/workflows/main.yaml
- .gitignore
- ci/docker-compose-azure-cc.yml
- ci/docker-compose-cluster.yml
- ci/docker-compose-okta-cc.yml
- ci/docker-compose-okta-users.yml
- ci/docker-compose-openai.yml
- ci/docker-compose-wcs.yml
- ci/docker-compose.yml
- ci/run_dependencies.sh
- ci/stop_dependencies.sh
- src/cluster/journey.test.ts
- src/data/creator.ts
- src/data/updater.ts
- src/graphql/journey.test.ts
- src/graphql/nearImage.ts
- src/graphql/nearMedia.ts
- src/graphql/nearObject.ts
- src/graphql/nearText.ts
- src/graphql/nearVector.ts
- src/openapi/schema.ts
- src/schema/journey.test.ts
- test.sh
This PR adds support for utilising the new named vectors feature of Weaviate landing in `1.24`
This includes:
- creating classes with named vector configurations
- creating and updating objects with named vectors
- querying for objects by the specific named vectors
> Add support for named vectors in 1.24 release

- src/graphql/hybrid.ts
- src/graphql/journey.test.ts
Fixes [113](https://github.com/weaviate/typescript-client/issues/113).
> Add support for target vectors in hybrid queries

- .github/workflows/main.yaml
- src/collections/aggregate/index.ts
- src/collections/collection/index.ts
- src/collections/integration.test.ts
- src/connection/gql.ts
- src/connection/grpc.ts
- src/connection/http.ts
- src/index.ts
- Add `collection.exists()` method as shortcut for `collections.exists(name: string)`
- Provide `client.close()` method to allow cleaning of resource
- Fix aggregate typing bug
> Respond to beta user feedback

- src/collections/aggregate/integration.test.ts
- src/collections/cluster/integration.test.ts
- src/collections/config/integration.test.ts
- src/collections/data/integration.test.ts
- src/collections/filters/integration.test.ts
- src/collections/generate/integration.test.ts
- src/collections/integration.test.ts
- src/collections/iterator/integration.test.ts
- src/collections/query/integration.test.ts
- src/collections/sort/integration.test.ts
- src/collections/tenants/integration.test.ts
- src/connection/auth.ts
- src/connection/helpers.ts
- src/index.ts
- Changes `ClientParams` to have a `connectionParams: ConnectionParams` field
- Moves `rest` and `grpc` fields inside `connectionParams`
- Renames `rest` to `http`
> Align `ClientParams` with Python client

- package-lock.json
- package.json
This PR adds `graphql` as a direct dependency to avoid installation problems due to it being a peer dependency of `graphql-request`
> Add graphql as direct dependency

- src/collections/configure/index.ts
- src/openapi/schema.ts
Adds support for the `kagome_kr` tokenizer (to be added in `1.26`)
https://github.com/weaviate/weaviate/pull/5211/files
> Add support for the kagome_kr tokenizer

- src/collections/data/index.ts
- src/collections/data/integration.test.ts
- src/collections/serialize/index.ts
The `v3` client currently doesn't handle the edge case where a collection is configured using the single vectorizer per collection syntax and has been upgraded to Weaviate `>=v1.24.0`. As such, it fails to insert BYoV for such collections
This PR changes the object insertion to send the provided vector in both channels to handle each use-case
Closes https://github.com/weaviate/typescript-client/issues/167
> Send vectors optimistically to handle legacy vectorizers in >1.24.0

- src/collections/query/integration.test.ts
- src/collections/query/types.ts
- src/collections/serialize/index.ts
Adds the new `Bm25QueryProperty<T>` type for use when defining weighted keyword searches in BM25 and Hybrid queries. It maps internally to the `prop^w` string syntax expected by Weaviate
Closes https://github.com/weaviate/typescript-client/issues/178
> Add `Bm25QueryProperty` type for use in weighted `.bm25` and `.hybrid`

- src/collections/config/types/generative.ts
- src/collections/config/types/reranker.ts
- src/collections/config/types/vectorizer.ts
- src/collections/configure/generative.ts
- src/collections/configure/reranker.ts
- src/collections/configure/types/generative.ts
- src/collections/configure/types/vectorizer.ts
- src/collections/configure/unit.test.ts
- src/collections/configure/vectorizer.ts
- src/collections/index.ts
This PR adds support for the following modules:
It also fixes the docstrings of all modules and changes them to point to the new modules provider https://weaviate.io documentation
Closes:
- https://github.com/weaviate/typescript-client/issues/185
- https://github.com/weaviate/typescript-client/issues/187
- https://github.com/weaviate/typescript-client/issues/190
- https://github.com/weaviate/typescript-client/issues/191
> Add support for new modules

- ci/docker-compose.yml
- src/backup/backupCreateStatusGetter.ts
- src/backup/backupCreator.ts
- src/backup/backupGetter.ts
- src/backup/backupRestoreStatusGetter.ts
- src/backup/backupRestorer.ts
- src/collections/backup/client.ts
- src/collections/backup/collection.ts
- src/collections/backup/index.ts
- src/collections/backup/integration.test.ts
- src/collections/backup/types.ts
- src/collections/backup/unit.test.ts
- src/errors.ts
- src/openapi/schema.ts
- Add `backup.cancel`
- make non-BC changes to backup types
- improve error throwing in backup methods
- improve docs of backup types
- use mocks to test `waitForCompletion` flow with cancelled backups
> Support backup cancellation

- package-lock.json
- package.json
- src/connection/grpc.ts
- src/grpc/base.ts
- src/grpc/batcher.ts
- src/grpc/retry.ts
- src/grpc/searcher.ts
- src/grpc/tenantsManager.ts
Closes https://github.com/weaviate/typescript-client/issues/212
Instead of using custom grpc keep alive options, as was attempted in https://github.com/weaviate/typescript-client/pull/216, which may not be fully generalisable to all cases, this PR introduces `nice-grpc-client-middleware-retry` to instead simply retry any `UNAVAILABLE` errors with exponential backoff and `N=5` in the hope that such transient errors go away
> Use `nice-grpc-client-middleware-retry` for auto-retry of UNAVAILABLE grpc error

- src/collections/config/types/vectorizer.ts
- src/collections/configure/types/vectorizer.ts
- src/collections/configure/unit.test.ts
- src/collections/configure/vectorizer.ts
Closes https://github.com/weaviate/typescript-client/issues/221
> Add `configure.multi2VecCohere` factory method and types for the module

- src/collections/config/types/generative.ts
- src/collections/config/types/vectorizer.ts
- src/collections/configure/generative.ts
- src/collections/configure/types/generative.ts
- src/collections/configure/types/vectorizer.ts
- src/collections/configure/unit.test.ts
- src/collections/configure/vectorizer.ts
- src/proto/v1/generative.ts
Closes https://github.com/weaviate/typescript-client/issues/215
> Remove all references to OctoAI since they've shutdown

- src/collections/collection/index.ts
Closes https://github.com/weaviate/typescript-client/issues/186
> Adds `await collection.length()` shorthand method

- src/collections/configure/types/base.ts
> Ensures proper type association for `nestedProperties` in data type configurations
- Fix #203 
- - Previously, even primitive types like string or boolean could accept `nestedProperties` when `strict` mode was enabled, which is technically invalid.
- - When strict mode was disabled, valid cases involving objects also triggered errors.
Primitive types (`string`, `boolean`, etc.) erroneously accept `nestedProperties`, which is technically impossible.
Example (Invalid but currently allowed):
```typescript
const invalidConfig = {
name: 'Example',
dataType: 'text', // Primitive type
nestedProperties: [
{ name: 'Invalid', dataType: 'number' }, // ❌ should trigger a typescript error here, but doesn't
],
};
```
Both invalid and valid configurations trigger errors.
For instance, even proper …
> Improve nestedProperties' type configuration

- src/collections/configure/types/base.ts
This PR adjusts the generic of the `nestedProperties` field in `NestedDataTypeConfig` when `dataType` has the type `ObjectDataType` so that there are no compiler errors when `strict: false` when defining the `nestedProperties` field of a property type with `object` or `object[]` data type
In short, by making use of `NestedPropertyConfigCreate`, the same issue of `strict: false` not resolving the conditional type `T extends undefined ? ... : ...` is encountered. With this change, we avoid that and so remove the bug
> Adjust generic for `NestedDataTypeConfig` when `ObjectDataType`

- package-lock.json
- package.json
- src/collections/config/types/vectorizer.ts
- src/collections/configure/types/vectorizer.ts
- src/collections/configure/unit.test.ts
- src/collections/configure/vectorizer.ts
- src/connection/helpers.test.ts
- src/connection/helpers.ts
- src/connection/journey.test.ts
adds `text2vec-weaviate` vectorizer
> Text2vec weaviate

- ci/docker-compose.yml
- src/collections/aggregate/index.ts
- src/collections/config/classes.ts
- src/collections/config/integration.test.ts
- src/collections/config/types/index.ts
- src/collections/config/unit.test.ts
- src/collections/configure/index.ts
- Allow updating of generative and reranker configs dynamically
- Fix typing issues with generative and reranker configs
Closes https://github.com/weaviate/typescript-client/issues/222
> Improve generative/reranker config UX

- src/connection/helpers.ts
- src/connection/unit.test.ts
- src/errors.ts
- src/grpc/base.ts
- src/grpc/batcher.ts
- src/grpc/searcher.ts
- src/grpc/tenantsManager.ts
- Actually pass timeout config from helpers to clientMaker
- Rearrange error handling in methods to throw better exceptions
Closes https://github.com/weaviate/typescript-client/issues/253, https://github.com/weaviate/typescript-client/issues/244
> Improve UX of using timeouts

- .github/workflows/main.yaml
- src/index.ts
- src/openapi/types.ts
- src/roles/index.ts
- src/roles/integration.test.ts
- src/roles/types.ts
- src/roles/util.ts
- src/users/index.ts
- src/users/integration.test.ts
- src/users/types.ts
- Split `roles` with `users`
- make `actions` an array inside `permissions`
- rename several methods to be aligned with py client in a non-BC way
- only run roles/users tests for `>1.29` due to no BC
> Refactor `roles` namespace, adding `users`, to align with new Python API

- src/connection/grpc.ts
- src/connection/helpers.test.ts
- src/connection/helpers.ts
- src/connection/http.ts
Always pass Embedding Service headers so it works also via OIDC auth
> always pass embedding service headers

- src/utils/base64.test.ts
- src/utils/base64.ts
- Fix #232 
@tsmith023  can you have a look, please?
> feat: add the support of URLs for the `nearImage()` method

- .github/workflows/main.yaml
- src/roles/index.ts
- src/roles/integration.test.ts
- src/users/index.ts
- src/users/integration.test.ts
Follow-up for #278 
Unfortunately, the initial PR adding dynamic user management had a couple of blunders, which I'm addressing in this PR.
- ‼️ **Bring back `roles.assignedUserIds`** -- I'd got a false impression that this method was removed in the Python client and [replaced it with _userAssignments_](https://github.com/weaviate/typescript-client/pull/278/commits/d61c30fbf3ab0ea18225d86f734ba6287d6f7fdd) rather than deprecating it.
- Return `false` on HTTP 409 Conflict from /activate and /deactivate endpoints.
- Add deprecation notices to `users.assignRoles`, `users.revokeRoles`, and `roles.assignedUserIds`
> fix: revert breaking change and add deprecation notices

- src/collections/config/types/generative.ts
- src/collections/config/types/reranker.ts
- src/collections/config/types/vectorizer.ts
- src/collections/configure/reranker.ts
- src/collections/configure/unit.test.ts
- `reranker-nvidia` when configuring collections
- missing `baseURL` options in certain modules
- unit tests for reranker configuration
Closes https://github.com/weaviate/typescript-client/issues/262
> Adds support to modules for

- .github/workflows/main.yaml
- src/openapi/schema.ts
- src/roles/util.ts
- src/users/index.ts
- src/users/integration.test.ts
- src/users/types.ts
This PR adds optional `includeLastUsedTime` parameter to `users.db.byName` and `users.db.listAll` methods, which controls if the last login time will be retrieved for the users.
Additionally, `UserDB` model has 2 new fields:
- `createdAt`: returned for all users (provided server is `v1.30.1` and above)
- `apiKeyFirstLetters`: returned whenever request is made by the cluster admin (intended to be displayed in the WCS Console)
Updated `openapi.ts` schema spec.
> feat(v1.30.1): retrieve users' last login time and preview API keys

- .github/workflows/main.yaml
- package-lock.json
- package.json
`npm login` is an interactive command, it should not be part of the CI script.
Rolling back package version to 3.5.3, we'll bump the version on the next release attempt.
> fix: revert npm login

- .github/workflows/main.yaml
- src/collections/config/index.ts
- src/collections/config/integration.test.ts
- src/collections/config/utils.ts
- src/collections/configure/types/vectorizer.ts
- src/collections/index.ts
- src/collections/integration.test.ts
- src/schema/vectorAdder.ts
This PR:
- adds `collection.config.addVector` method to support creating new named vectors on the collection. Only named vectors can be created and existing named vectors cannot be modified.
The method accepts the same arguments as `collections.create(... { vectorizers: XXX })` with the exception that anonymous vectors are not permitted, e.g. `vectorizer.none()`. 
- fixes a bug whereby passing a vector with a custom name as a `single object` and passing it as an array `[single object]` to `collections.create()` would result in 2 different behaviors: custom name changed to `default` vs custom name preserved.
```ts
// Both cases should generate vectorConfig: { 'custom': {...} }
collections.create(..., { vectorizers: vectorizer.none('custom') });
collections.create(..., { vectorizers: …
```
> Support adding named vectors to a collection

- .github/workflows/main.yaml
- src/collections/query/index.ts
- src/collections/query/integration.test.ts
- src/collections/query/types.ts
- src/collections/query/utils.ts
- src/collections/serialize/index.ts
- src/proto/v1/base_search.ts
This PR adds an optional search operator argument to BM25 and Hybrid queries that provides the new `minimum_should_match` semantics.
```ts
collection.query.hybrid(..., { bm25Operator: BM25Operator.and({ minimumMatch: 5 })});
collection.query.bm25(..., { operator: BM25Operator.or({ minimumMatch: 3 })});
```
> BM25 and Hybrid search with minimum_should_match

- .github/workflows/main.yaml
- src/collections/config/index.ts
- src/collections/config/integration.test.ts
- src/collections/config/types/vectorIndex.ts
- src/collections/config/utils.ts
- src/collections/configure/parsing.ts
- src/collections/configure/types/vectorIndex.ts
- src/collections/configure/vectorIndex.ts
- src/collections/data/integration.test.ts
- src/collections/index.ts
- src/schema/journey.test.ts
RQ can be configured so:
```ts
weaviate.configure.vectorIndex.quantizer.rq({ bits: 6, rescoreLimit: 20 });
```
When updating, it is only possible to update `rescoreLimit`.
> feat: Add support for RQ

- src/alias/index.ts
- src/alias/journey.test.ts
- src/alias/types.ts
- src/index.ts
- src/openapi/schema.ts
- src/openapi/types.ts
- src/roles/index.ts
- src/roles/integration.test.ts
- src/roles/types.ts
- src/roles/util.ts
> ➡️ Merge after #315. There are some CI configuration updates and test fixes.
This PR adds API for managing collection aliases and extends the set of permissions with AliasPermission.
Manage aliases
```ts
client.alias.create({ collection: "Pizza", alias: "PizzaPie" });
client.alias.listAll();
client.alias.listAll("Pizza"); // list aliases defined for Pizza collection
client.alias.get("PizzaPie");
client.alias.update({ alias: "PizzaPie", newTargetCollectionName: "Langos" });
client.alias.delete("PizzaPie");
```
Manage alias permissions
```ts
weaviate.permissions.aliases({
alias: ["PizzaPie", "PizzaWhy"],
create: true,
read: true,
update: true,
delete: true,
})
```
> feat: Collection aliasing

- src/collections/config/types/vectorizer.ts
- src/collections/configure/types/vectorizer.ts
- src/collections/configure/unit.test.ts
- src/collections/configure/vectorizer.ts
- deprecate `text2vec-contextionary`
- add `text2vec-model2vec`, which is a replacement for `text2vec-contextionary`
- add `dimensions` parameter to `text2vec-transformers`
> Make improvements to the modules system

- src/connection/grpc.ts
- When using Weaviate Embedding service, gRPC aggregate calls were missing the required X-Weaviate-Cluster-Url header while search and batch operations included it correctly. This caused aggregate queries to fail with "no cluster URL found in request header" errors.
> fix: missing X-Weaviate-Cluster-Url header in gRPC aggregations

- src/collections/config/utils.ts
In some edge cases the cluster may not have Multi Tenancy configuration. This will return false for those cases.
> Make Multi Tenancy config more resilient
